-- MySQL Script generated by MySQL Workbench
-- Thu Aug 31 08:31:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CadastroPessoas` DEFAULT CHARACTER SET utf8 ;
USE `CadastroPessoas` ;

-- -----------------------------------------------------
-- Table `mydb`.`CadastroUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CadastroPessoas`.`CadastroUsuario` (
  `idCadastroUsuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCadastroUsuario`),
  UNIQUE INDEX `idCadastroUsuario_UNIQUE` (`idCadastroUsuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CadastroPessoas`.`Pessoa` (
  `idPessoa` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Data_nascimento` DATE NULL,
  `CPF` INT NULL,
  `RG` INT NULL,
  `Email` VARCHAR(45) NULL,
  `Foto` VARCHAR(45) NULL,
  `CadastroUsuario_idCadastroUsuario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idPessoa`),
  UNIQUE INDEX `idPessoa_UNIQUE` (`idPessoa` ASC),
  INDEX `fk_Pessoa_CadastroUsuario_idx` (`CadastroUsuario_idCadastroUsuario` ASC),
  CONSTRAINT `fk_Pessoa_CadastroUsuario`
    FOREIGN KEY (`CadastroUsuario_idCadastroUsuario`)
    REFERENCES `CadastroPessoas`.`CadastroUsuario` (`idCadastroUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
